//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaVI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasPorCobrar
    {
        public int IdCuenta { get; set; }
        public string IdCliente { get; set; }
        public string IdVendedor { get; set; }
        public int IdFactura { get; set; }
        public decimal PrecioTotal { get; set; }
        public decimal Pago { get; set; }
        public decimal Restante { get; set; }
    }
}
